### ISSUE TITLE
Can I use your theme as my site template?

### ISSUE THREAD

**Issue by nmrony** [IronSummitMedia/startbootstrap-clean-blog#12]
As per definition this is not an issue. I like your template and it's simplicity. Can I use it for my personal site blog. nothing professional. I honor copyrights.

**Comment by ugcoder** [comment]
//Copyright 2013-2015 Iron Summit Media Strategies, LLC. Code released under the Apache 2.0 license.//
So, you can use.

**Comment by nmrony** [comment]
Many Thanks of you

**Comment by ugcoder** [comment]
Welcome.
